language: python
python:
- '2.7'
- '3.4'
- '3.5'
script:
- pip install -U flake8
- pip install -r requirements.txt
- python setup.py install
- flake8 galaxyxml
- python examples/example.py | xmllint --pretty 1 - > tmp.xml
- diff tmp.xml examples/tool.xml
- nosetests --with-coverage --cover-package=galaxyxml
deploy:
  provider: pypi
  user: erasche
  password:
    secure: UUC6+XBMr3SHz8V5UeCBsZ7mmjoRukTkqyYGlr1HfCB6RukpnAM4eJ4Y/WMgiNuevah5dkQV/SmPe/u1MzCXZa4x6qz6t1KXg1l7+wYfOR/nvEgxOJjpOlNjqJrKay1mNGoxj8D9q+Sg7294bho6/61BZBrKQQT1WeM9mdH+ex0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: erasche/galaxyxml
