language: python

python:
- '2.7'
- '3.4'
- '3.5'

script:
- pip install -U flake8
- pip install -r requirements.txt
- python setup.py install
- flake8 galaxyxml
- python examples/example.py | xmllint --pretty 1 - > tmp.xml
- diff tmp.xml examples/tool.xml

deploy:
- provider: pypi
  user: erasche
  password:
    secure: PjtJXEgtAjPKU/dqlodk/PxR9V6izRc7Ku7Q0jJG8eQcr+u3tGTKWtGSO9ULclfEzRrZmC4ndgJMklV6TWpT9sRJon9+itOrBXxiQMHoqfZ3tRw7Iqgo4sRoTQSu810DYqgWTCTYZLkPGiHjeinAfl9tUQ2jqyhulUPOdssM2UQ=
  on:
    tags: true
    all_branches: true
    distributions: sdist bdist_wheel
    repo: erasche/galaxyxml
