language: python
python:
- '3.6'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-utils
script:
- pip install coverage
- pip install -U flake8 xmldiff
- pip install -r requirements.txt
- python setup.py install
- flake8 galaxyxml
- python examples/example.py | xmllint --pretty 1 - > tmp.xml
- xmldiff tmp.xml examples/tool.xml
- nosetests --with-coverage --cover-package=galaxyxml
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  distributions: sdist bdist_wheel
  edge: true
  skip_existing: true
